version: 1.0
publish: app
services:
  app:
    environment:
      NODE_ENV: production
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 8080
        public: 80
